services:
  openresty:
    image: openresty/openresty:1.27.1.2-0-alpine
    container_name: openresty
    command: [ "/usr/local/openresty/bin/openresty", "-g", "daemon off;", "-c", "/etc/nginx/nginx.conf" ]
    restart: unless-stopped
    ports:
      - "9080:9080"
      - "9081:9081"
      - "9082:9082"
    volumes:
      - ./conf:/etc/nginx:ro
      - ./logs:/var/log/nginx
      - ./html:/var/www/html:ro
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"
    networks:
      - openresty-network

networks:
  openresty-network:
    driver: bridge
